app_group:
  - read:
      path: /apps/filters.eda.nokia.com
      method: GET

patch:
  - update:
      path: /apps/filters.eda.nokia.com/v1alpha1/namespaces/{namespace}/controlplanefilters/{name}
      method: PATCH
  - update:
      path: /apps/filters.eda.nokia.com/v1alpha1/namespaces/{namespace}/filters/{name}
      method: PATCH

resource_history:
  - read:
      path: /apps/filters.eda.nokia.com/v1alpha1/namespaces/{namespace}/controlplanefilters/{name}/_revs
      method: GET
  - read:
      path: /apps/filters.eda.nokia.com/v1alpha1/namespaces/{namespace}/filters/{name}/_revs
      method: GET

resource_list:
  - read:
      path: /apps/filters.eda.nokia.com/v1alpha1
      method: GET

resource_topology:
  - read:
      path: /apps/filters.eda.nokia.com/v1alpha1/namespaces/{namespace}/controlplanefilters/{name}/_topology
      method: GET
  - read:
      path: /apps/filters.eda.nokia.com/v1alpha1/namespaces/{namespace}/filters/{name}/_topology
      method: GET

status:
  - delete:
      path: /apps/filters.eda.nokia.com/v1alpha1/namespaces/{namespace}/controlplanefilters/{name}
      method: DELETE
  - delete:
      path: /apps/filters.eda.nokia.com/v1alpha1/namespaces/{namespace}/filters/{name}
      method: DELETE

ui_result:
  - read:
      path: /apps/filters.eda.nokia.com/v1alpha1/_ui/{pathname}
      method: GET

com.nokia.eda.filters.v1alpha1.control_plane_filter:
  - create:
      path: /apps/filters.eda.nokia.com/v1alpha1/namespaces/{namespace}/controlplanefilters
      method: POST
  - read:
      path: /apps/filters.eda.nokia.com/v1alpha1/namespaces/{namespace}/controlplanefilters/{name}
      method: GET
  - update:
      path: /apps/filters.eda.nokia.com/v1alpha1/namespaces/{namespace}/controlplanefilters/{name}
      method: PUT

com.nokia.eda.filters.v1alpha1.control_plane_filter_list:
  - read:
      path: /apps/filters.eda.nokia.com/v1alpha1/controlplanefilters
      method: GET
  - read:
      path: /apps/filters.eda.nokia.com/v1alpha1/namespaces/{namespace}/controlplanefilters
      method: GET
  - delete:
      path: /apps/filters.eda.nokia.com/v1alpha1/namespaces/{namespace}/controlplanefilters
      method: DELETE

com.nokia.eda.filters.v1alpha1.control_plane_filter_deleted_resources:
  - read:
      path: /apps/filters.eda.nokia.com/v1alpha1/namespaces/{namespace}/controlplanefilters/_deleted
      method: GET

com.nokia.eda.filters.v1alpha1.filter:
  - create:
      path: /apps/filters.eda.nokia.com/v1alpha1/namespaces/{namespace}/filters
      method: POST
  - read:
      path: /apps/filters.eda.nokia.com/v1alpha1/namespaces/{namespace}/filters/{name}
      method: GET
  - update:
      path: /apps/filters.eda.nokia.com/v1alpha1/namespaces/{namespace}/filters/{name}
      method: PUT

com.nokia.eda.filters.v1alpha1.filter_list:
  - read:
      path: /apps/filters.eda.nokia.com/v1alpha1/filters
      method: GET
  - read:
      path: /apps/filters.eda.nokia.com/v1alpha1/namespaces/{namespace}/filters
      method: GET
  - delete:
      path: /apps/filters.eda.nokia.com/v1alpha1/namespaces/{namespace}/filters
      method: DELETE

com.nokia.eda.filters.v1alpha1.filter_deleted_resources:
  - read:
      path: /apps/filters.eda.nokia.com/v1alpha1/namespaces/{namespace}/filters/_deleted
      method: GET

totalPaths: 15
totalSchemas: 38
usedSchemas: 13
unusedSchemas: 25
unusedSchemaList:
  - AppGroupVersion
  - ErrorIndex
  - ErrorItem
  - ErrorResponse
  - K8SPatchOp
  - OverlayState
  - Resource
  - ResourceHistoryEntry
  - StatusDetails
  - TopoAttrMetadata
  - TopoElemMetadata
  - TopoLinkEndpoint
  - TopoNodeGrouping
  - TopoOverlayEndpoint
  - TopoOverlayEndpointState
  - TopoOverlayLink
  - TopoOverlayLinkState
  - TopoOverlayNode
  - TopoOverlayNodeState
  - TopoSchema
  - Topology
  - com.nokia.eda.filters.v1alpha1.ControlPlaneFilter_DeletedResourceEntry
  - com.nokia.eda.filters.v1alpha1.ControlPlaneFilter_metadata
  - com.nokia.eda.filters.v1alpha1.Filter_DeletedResourceEntry
  - com.nokia.eda.filters.v1alpha1.Filter_metadata
